baseURL = "https://mmjha.github.io/"
languageCode = "en-us"
title = "hJ"
theme = "hugo-ink"
paginate = 5

copyright = "© Copyright notice"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = "hJ BloG"

[params]
	subtitle = "hJ, BloG [github.com/mmjha](https://github.com/mmjha)"

	# Optional 64x64 avatar image.
	avatar = "https://cdn.pixabay.com/photo/2016/09/27/05/35/letter-1697604_1280.png"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	# Content types to disable comment on.
	isComment = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.
	
	# 
  	mainSections = ["posts", "projects", "ps"]

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Post"
url = "/posts"
weight = 3

[[menu.main]]
name = "Project"
url = "/projects"
weight = 4

[[menu.main]]
name = "PS"
url = "/ps"
weight = 5

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 6

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/mmjha"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

